spring.application.name=ai-service
ai.api.key=${AI_API_KEY}

# Ändra sökvägen till något snyggt (valfritt)
springdoc.swagger-ui.path=/swagger-ui.html
# Sortera endpoints efter metod (GET, POST etc)
springdoc.swagger-ui.operationsSorter=alpha
